apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "opsaix.fullname" . }}-chroma-pvc
  labels:
    {{- include "opsaix.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}